packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  "@parcel/watcher": true
  "@scarf/scarf": true
  bcrypt: true
  esbuild: true
  unrs-resolver: true
onlyBuiltDependencies:
  - "@parcel/watcher"
  - unrs-resolver
  - bcrypt
  - "@scarf/scarf"
